-- Hapus semua data dummy di seluruh tabel
TRUNCATE TABLE members CASCADE;
TRUNCATE TABLE programs CASCADE;
TRUNCATE TABLE agendas CASCADE;
TRUNCATE TABLE attendance CASCADE;
TRUNCATE TABLE evaluations CASCADE;
TRUNCATE TABLE finance_transactions CASCADE;
TRUNCATE TABLE dues CASCADE;
TRUNCATE TABLE letters CASCADE;
TRUNCATE TABLE minutes CASCADE;
TRUNCATE TABLE archives CASCADE;
